services:
  - type: web
    name: pe-platform-algeria-backend
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeployTrigger: commit

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGIN
        value: https://ahmedkamel061992-dot.github.io
      - key: SUPABASE_BUCKET
        value: payment-receipts
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
