const API='https://pe-platform-algeria.onrender.com';
const $=id=>document.getElementById(id);
let token=localStorage.getItem('pe_token');
function message(t){$('msg').textContent=t;}
async function jsonFetch(path,options={}){const r=await fetch(API+path,options);let d={};try{d=await r.json()}catch{};if(!r.ok)throw new Error(d.error||`خطأ HTTP ${r.status}`);return d;}
async function register(){message('جارٍ إنشاء الحساب...');try{const d=await jsonFetch('/api/v1/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('name').value.trim(),email:$('email').value.trim(),password:$('password').value})});token=d.accessToken;localStorage.setItem('pe_token',token);await check();}catch(e){message(e.message);}}
async function login(){message('جارٍ تسجيل الدخول...');try{const d=await jsonFetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});token=d.accessToken;localStorage.setItem('pe_token',token);await check();}catch(e){message(e.message);}}
async function check(){if(!token)return;try{const d=await jsonFetch('/api/v1/me',{headers:{Authorization:`Bearer ${token}`}});$('auth').classList.add('hidden');if(d.user.status==='ACTIVE'){message('تم التفعيل. جارٍ فتح المنصة...');const r=await fetch(API+'/api/v1/app',{headers:{Authorization:`Bearer ${token}`}});if(!r.ok)throw new Error('تعذر فتح المنصة.');const html=await r.text();document.open();document.write(html);document.close();}else{$('pay').classList.remove('hidden');message(d.user.status==='PENDING_REVIEW'?'تم استلام الوصل. الحساب قيد مراجعة المسؤول.':'يجب إتمام الاشتراك وإرسال وصل الدفع.');}}catch(e){localStorage.removeItem('pe_token');token=null;message(e.message);}}
async function sendReceipt(){const f=$('receipt').files[0];if(!f)return message('اختر وصل الدفع أولًا.');message('جارٍ إرسال الوصل...');try{const fd=new FormData();fd.append('receipt',f);const d=await jsonFetch('/api/v1/payments/receipt',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});message(d.message||'تم إرسال الوصل بنجاح.');$('receipt').value='';}catch(e){message(e.message);}}
$('registerBtn').addEventListener('click',register);$('loginBtn').addEventListener('click',login);$('receiptBtn').addEventListener('click',sendReceipt);$('checkBtn').addEventListener('click',check);window.addEventListener('error',e=>message('حدث خطأ في الصفحة: '+e.message));check();
