const API='https://pe-platform-algeria.onrender.com';
const TOKEN_KEY='pe_platform_access_token_v3';
const $=id=>document.getElementById(id);
// Invalidate tokens from all previous gateway versions.
localStorage.removeItem('pe_token');
localStorage.removeItem('pe_platform_access_token_v2');
let token=localStorage.getItem(TOKEN_KEY)||null;
function message(t){const el=$('msg');if(el)el.textContent=t;}
async function jsonFetch(path,options={}){const r=await fetch(API+path,{...options,cache:'no-store'});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||`خطأ HTTP ${r.status}`);return d;}
function setToken(t){token=t;localStorage.setItem(TOKEN_KEY,t);}
function clearToken(){token=null;localStorage.removeItem(TOKEN_KEY);}
function showPay(text='يجب إتمام الاشتراك وإرسال وصل الدفع.'){$('auth').classList.add('hidden');$('pay').classList.remove('hidden');message(text);}
async function register(){message('جارٍ إنشاء الحساب...');try{const d=await jsonFetch('/api/v1/auth/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('name').value.trim(),email:$('email').value.trim(),password:$('password').value})});setToken(d.accessToken);showPay('تم إنشاء الحساب بنجاح. الاشتراك: 1000 دج. اختر الوصل ثم اضغط إرسال.');}catch(e){message(e.message);}}
async function login(){message('جارٍ تسجيل الدخول...');try{const d=await jsonFetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value.trim(),password:$('password').value})});setToken(d.accessToken);await check();}catch(e){clearToken();message(e.message);}}
async function check(){if(!token)return;try{const d=await jsonFetch('/api/v1/me',{headers:{Authorization:`Bearer ${token}`}});if(d.user.status==='ACTIVE'){message('تم التفعيل. جارٍ فتح المنصة...');const r=await fetch(API+'/api/v1/app',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});if(!r.ok)throw new Error('تعذر فتح المنصة.');document.open();document.write(await r.text());document.close();}else showPay(d.user.status==='PENDING_REVIEW'?'تم استلام الوصل. الحساب قيد مراجعة المسؤول.':'تم تسجيل الدخول. الاشتراك: 1000 دج. اختر وصل الدفع ثم اضغط إرسال.');}catch(e){clearToken();$('auth').classList.remove('hidden');$('pay').classList.add('hidden');message(e.message);}}
async function sendReceipt(){if(!token)return message('انتهت جلسة الدخول. سجّل الدخول من جديد.');const f=$('receipt').files[0];if(!f)return message('اختر وصل الدفع أولًا.');if(f.size>8*1024*1024)return message('حجم الملف يجب ألا يتجاوز 8 ميغابايت.');message('جارٍ إرسال الوصل...');try{await jsonFetch('/api/v1/me',{headers:{Authorization:`Bearer ${token}`}});const fd=new FormData();fd.append('receipt',f,f.name);const d=await jsonFetch('/api/v1/payments/receipt',{method:'POST',headers:{Authorization:`Bearer ${token}`},body:fd});message(d.message||'تم إرسال الوصل بنجاح.');$('receipt').value='';}catch(e){message('تعذر إرسال الوصل: '+e.message);if(/الحساب غير موجود|جلسة الدخول غير صالحة|يجب تسجيل الدخول/.test(e.message))clearToken();}}
$('registerBtn').addEventListener('click',register);$('loginBtn').addEventListener('click',login);$('receiptBtn').addEventListener('click',sendReceipt);$('checkBtn').addEventListener('click',check);window.addEventListener('load',check);